export const userConstants = {
    // REGISTER
    REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
    // LOGIN
    LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
    // LOGOUT
    LOGOUT: 'USER_LOGOUT',
    // GETALL
    GETALL_REQUEST: 'USER_GETALL_REQUEST',
    GETALL_SUCCESS: 'USER_GETALL_SUCCESS',
    GETALL_FAILURE: 'USER_GETALL_FAILURE',
    // GETUSER
    GETUSER_REQUEST: 'USER_GETUSER_REQUEST',
    GETUSER_SUCCESS: 'USER_GETUSER_SUCCESS',
    GETUSER_FAILURE: 'USER_GETUSER_FAILURE',
    // DELETE
    DELETE_REQUEST: 'USER_DELETE_REQUEST',
    DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
    DELETE_FAILURE: 'USER_DELETE_FAILURE'
};